FROM nvcr.io/nvidia/pytorch:24.03-py3

# install loadgen
RUN cd /tmp && \
    git clone --recursive https://github.com/mlcommons/inference && \
    cd inference/loadgen && \
    pip install pybind11 && \
    CFLAGS="-std=c++14" python setup.py install && \
    rm -rf mlperf

RUN pip install Cython
RUN pip install scikit-image
RUN pip install tqdm
RUN pip install faster-coco-eval
RUN pip install torchinfo
RUN pip install torchmetrics
RUN apt-get update
RUN apt-get install -y libgl1-mesa-glx


